### ISSUE TITLE
微信PC版无法使用~

### ISSUE THREAD

**Issue by zliuzz** [Fixels/Eleditor#8]
RT 电脑版微信

**Comment by 1vanLuo** [comment]
原因是作者在js里面引用了ES6的assign，而PC微信浏览器不支持ES6语法，你自己把它改成jQuery的拷贝方法就行了
![image](https://user-images.githubusercontent.com/29398278/43813675-48176ec2-9af9-11e8-8f44-dba8952f4548.png)

**Comment by zliuzz** [comment]
灰常感谢~
